// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RTSPROTOCOL_RTS_NETWORK_H_
#define FLATBUFFERS_GENERATED_RTSPROTOCOL_RTS_NETWORK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace rts {
namespace network {

struct AttackCmd;
struct AttackCmdBuilder;
struct AttackCmdT;

struct RetreatCmd;
struct RetreatCmdBuilder;
struct RetreatCmdT;

struct CounterAttackCmd;
struct CounterAttackCmdBuilder;
struct CounterAttackCmdT;

struct SetRatioCmd;
struct SetRatioCmdBuilder;
struct SetRatioCmdT;

struct BuyUrbanizationCmd;
struct BuyUrbanizationCmdBuilder;
struct BuyUrbanizationCmdT;

struct PlayerCommand;
struct PlayerCommandBuilder;
struct PlayerCommandT;

struct RLERun;

struct ChunkDelta;
struct ChunkDeltaBuilder;
struct ChunkDeltaT;

struct TickDelta;
struct TickDeltaBuilder;
struct TickDeltaT;

struct UdpStatePacket;
struct UdpStatePacketBuilder;
struct UdpStatePacketT;

struct HandshakeRequest;
struct HandshakeRequestBuilder;
struct HandshakeRequestT;

struct HandshakeResponse;
struct HandshakeResponseBuilder;
struct HandshakeResponseT;

struct NackRequest;
struct NackRequestBuilder;
struct NackRequestT;

struct KeyframeSnapshot;
struct KeyframeSnapshotBuilder;
struct KeyframeSnapshotT;

struct TcpMessage;
struct TcpMessageBuilder;
struct TcpMessageT;

enum CommandPayload : uint8_t {
  CommandPayload_NONE = 0,
  CommandPayload_AttackCmd = 1,
  CommandPayload_RetreatCmd = 2,
  CommandPayload_CounterAttackCmd = 3,
  CommandPayload_SetRatioCmd = 4,
  CommandPayload_BuyUrbanizationCmd = 5,
  CommandPayload_MIN = CommandPayload_NONE,
  CommandPayload_MAX = CommandPayload_BuyUrbanizationCmd
};

inline const CommandPayload (&EnumValuesCommandPayload())[6] {
  static const CommandPayload values[] = {
    CommandPayload_NONE,
    CommandPayload_AttackCmd,
    CommandPayload_RetreatCmd,
    CommandPayload_CounterAttackCmd,
    CommandPayload_SetRatioCmd,
    CommandPayload_BuyUrbanizationCmd
  };
  return values;
}

inline const char * const *EnumNamesCommandPayload() {
  static const char * const names[7] = {
    "NONE",
    "AttackCmd",
    "RetreatCmd",
    "CounterAttackCmd",
    "SetRatioCmd",
    "BuyUrbanizationCmd",
    nullptr
  };
  return names;
}

inline const char *EnumNameCommandPayload(CommandPayload e) {
  if (::flatbuffers::IsOutRange(e, CommandPayload_NONE, CommandPayload_BuyUrbanizationCmd)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCommandPayload()[index];
}

template<typename T> struct CommandPayloadTraits {
  static const CommandPayload enum_value = CommandPayload_NONE;
};

template<> struct CommandPayloadTraits<rts::network::AttackCmd> {
  static const CommandPayload enum_value = CommandPayload_AttackCmd;
};

template<> struct CommandPayloadTraits<rts::network::RetreatCmd> {
  static const CommandPayload enum_value = CommandPayload_RetreatCmd;
};

template<> struct CommandPayloadTraits<rts::network::CounterAttackCmd> {
  static const CommandPayload enum_value = CommandPayload_CounterAttackCmd;
};

template<> struct CommandPayloadTraits<rts::network::SetRatioCmd> {
  static const CommandPayload enum_value = CommandPayload_SetRatioCmd;
};

template<> struct CommandPayloadTraits<rts::network::BuyUrbanizationCmd> {
  static const CommandPayload enum_value = CommandPayload_BuyUrbanizationCmd;
};

template<typename T> struct CommandPayloadUnionTraits {
  static const CommandPayload enum_value = CommandPayload_NONE;
};

template<> struct CommandPayloadUnionTraits<rts::network::AttackCmdT> {
  static const CommandPayload enum_value = CommandPayload_AttackCmd;
};

template<> struct CommandPayloadUnionTraits<rts::network::RetreatCmdT> {
  static const CommandPayload enum_value = CommandPayload_RetreatCmd;
};

template<> struct CommandPayloadUnionTraits<rts::network::CounterAttackCmdT> {
  static const CommandPayload enum_value = CommandPayload_CounterAttackCmd;
};

template<> struct CommandPayloadUnionTraits<rts::network::SetRatioCmdT> {
  static const CommandPayload enum_value = CommandPayload_SetRatioCmd;
};

template<> struct CommandPayloadUnionTraits<rts::network::BuyUrbanizationCmdT> {
  static const CommandPayload enum_value = CommandPayload_BuyUrbanizationCmd;
};

struct CommandPayloadUnion {
  CommandPayload type;
  void *value;

  CommandPayloadUnion() : type(CommandPayload_NONE), value(nullptr) {}
  CommandPayloadUnion(CommandPayloadUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(CommandPayload_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  CommandPayloadUnion(const CommandPayloadUnion &);
  CommandPayloadUnion &operator=(const CommandPayloadUnion &u)
    { CommandPayloadUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  CommandPayloadUnion &operator=(CommandPayloadUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~CommandPayloadUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = CommandPayloadUnionTraits<RT>::enum_value;
    if (type != CommandPayload_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, CommandPayload type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  rts::network::AttackCmdT *AsAttackCmd() {
    return type == CommandPayload_AttackCmd ?
      reinterpret_cast<rts::network::AttackCmdT *>(value) : nullptr;
  }
  const rts::network::AttackCmdT *AsAttackCmd() const {
    return type == CommandPayload_AttackCmd ?
      reinterpret_cast<const rts::network::AttackCmdT *>(value) : nullptr;
  }
  rts::network::RetreatCmdT *AsRetreatCmd() {
    return type == CommandPayload_RetreatCmd ?
      reinterpret_cast<rts::network::RetreatCmdT *>(value) : nullptr;
  }
  const rts::network::RetreatCmdT *AsRetreatCmd() const {
    return type == CommandPayload_RetreatCmd ?
      reinterpret_cast<const rts::network::RetreatCmdT *>(value) : nullptr;
  }
  rts::network::CounterAttackCmdT *AsCounterAttackCmd() {
    return type == CommandPayload_CounterAttackCmd ?
      reinterpret_cast<rts::network::CounterAttackCmdT *>(value) : nullptr;
  }
  const rts::network::CounterAttackCmdT *AsCounterAttackCmd() const {
    return type == CommandPayload_CounterAttackCmd ?
      reinterpret_cast<const rts::network::CounterAttackCmdT *>(value) : nullptr;
  }
  rts::network::SetRatioCmdT *AsSetRatioCmd() {
    return type == CommandPayload_SetRatioCmd ?
      reinterpret_cast<rts::network::SetRatioCmdT *>(value) : nullptr;
  }
  const rts::network::SetRatioCmdT *AsSetRatioCmd() const {
    return type == CommandPayload_SetRatioCmd ?
      reinterpret_cast<const rts::network::SetRatioCmdT *>(value) : nullptr;
  }
  rts::network::BuyUrbanizationCmdT *AsBuyUrbanizationCmd() {
    return type == CommandPayload_BuyUrbanizationCmd ?
      reinterpret_cast<rts::network::BuyUrbanizationCmdT *>(value) : nullptr;
  }
  const rts::network::BuyUrbanizationCmdT *AsBuyUrbanizationCmd() const {
    return type == CommandPayload_BuyUrbanizationCmd ?
      reinterpret_cast<const rts::network::BuyUrbanizationCmdT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyCommandPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CommandPayload type);
template <bool B = false>
bool VerifyCommandPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum TcpPayload : uint8_t {
  TcpPayload_NONE = 0,
  TcpPayload_PlayerCommand = 1,
  TcpPayload_HandshakeRequest = 2,
  TcpPayload_HandshakeResponse = 3,
  TcpPayload_NackRequest = 4,
  TcpPayload_KeyframeSnapshot = 5,
  TcpPayload_MIN = TcpPayload_NONE,
  TcpPayload_MAX = TcpPayload_KeyframeSnapshot
};

inline const TcpPayload (&EnumValuesTcpPayload())[6] {
  static const TcpPayload values[] = {
    TcpPayload_NONE,
    TcpPayload_PlayerCommand,
    TcpPayload_HandshakeRequest,
    TcpPayload_HandshakeResponse,
    TcpPayload_NackRequest,
    TcpPayload_KeyframeSnapshot
  };
  return values;
}

inline const char * const *EnumNamesTcpPayload() {
  static const char * const names[7] = {
    "NONE",
    "PlayerCommand",
    "HandshakeRequest",
    "HandshakeResponse",
    "NackRequest",
    "KeyframeSnapshot",
    nullptr
  };
  return names;
}

inline const char *EnumNameTcpPayload(TcpPayload e) {
  if (::flatbuffers::IsOutRange(e, TcpPayload_NONE, TcpPayload_KeyframeSnapshot)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTcpPayload()[index];
}

template<typename T> struct TcpPayloadTraits {
  static const TcpPayload enum_value = TcpPayload_NONE;
};

template<> struct TcpPayloadTraits<rts::network::PlayerCommand> {
  static const TcpPayload enum_value = TcpPayload_PlayerCommand;
};

template<> struct TcpPayloadTraits<rts::network::HandshakeRequest> {
  static const TcpPayload enum_value = TcpPayload_HandshakeRequest;
};

template<> struct TcpPayloadTraits<rts::network::HandshakeResponse> {
  static const TcpPayload enum_value = TcpPayload_HandshakeResponse;
};

template<> struct TcpPayloadTraits<rts::network::NackRequest> {
  static const TcpPayload enum_value = TcpPayload_NackRequest;
};

template<> struct TcpPayloadTraits<rts::network::KeyframeSnapshot> {
  static const TcpPayload enum_value = TcpPayload_KeyframeSnapshot;
};

template<typename T> struct TcpPayloadUnionTraits {
  static const TcpPayload enum_value = TcpPayload_NONE;
};

template<> struct TcpPayloadUnionTraits<rts::network::PlayerCommandT> {
  static const TcpPayload enum_value = TcpPayload_PlayerCommand;
};

template<> struct TcpPayloadUnionTraits<rts::network::HandshakeRequestT> {
  static const TcpPayload enum_value = TcpPayload_HandshakeRequest;
};

template<> struct TcpPayloadUnionTraits<rts::network::HandshakeResponseT> {
  static const TcpPayload enum_value = TcpPayload_HandshakeResponse;
};

template<> struct TcpPayloadUnionTraits<rts::network::NackRequestT> {
  static const TcpPayload enum_value = TcpPayload_NackRequest;
};

template<> struct TcpPayloadUnionTraits<rts::network::KeyframeSnapshotT> {
  static const TcpPayload enum_value = TcpPayload_KeyframeSnapshot;
};

struct TcpPayloadUnion {
  TcpPayload type;
  void *value;

  TcpPayloadUnion() : type(TcpPayload_NONE), value(nullptr) {}
  TcpPayloadUnion(TcpPayloadUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(TcpPayload_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  TcpPayloadUnion(const TcpPayloadUnion &);
  TcpPayloadUnion &operator=(const TcpPayloadUnion &u)
    { TcpPayloadUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  TcpPayloadUnion &operator=(TcpPayloadUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~TcpPayloadUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = TcpPayloadUnionTraits<RT>::enum_value;
    if (type != TcpPayload_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, TcpPayload type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  rts::network::PlayerCommandT *AsPlayerCommand() {
    return type == TcpPayload_PlayerCommand ?
      reinterpret_cast<rts::network::PlayerCommandT *>(value) : nullptr;
  }
  const rts::network::PlayerCommandT *AsPlayerCommand() const {
    return type == TcpPayload_PlayerCommand ?
      reinterpret_cast<const rts::network::PlayerCommandT *>(value) : nullptr;
  }
  rts::network::HandshakeRequestT *AsHandshakeRequest() {
    return type == TcpPayload_HandshakeRequest ?
      reinterpret_cast<rts::network::HandshakeRequestT *>(value) : nullptr;
  }
  const rts::network::HandshakeRequestT *AsHandshakeRequest() const {
    return type == TcpPayload_HandshakeRequest ?
      reinterpret_cast<const rts::network::HandshakeRequestT *>(value) : nullptr;
  }
  rts::network::HandshakeResponseT *AsHandshakeResponse() {
    return type == TcpPayload_HandshakeResponse ?
      reinterpret_cast<rts::network::HandshakeResponseT *>(value) : nullptr;
  }
  const rts::network::HandshakeResponseT *AsHandshakeResponse() const {
    return type == TcpPayload_HandshakeResponse ?
      reinterpret_cast<const rts::network::HandshakeResponseT *>(value) : nullptr;
  }
  rts::network::NackRequestT *AsNackRequest() {
    return type == TcpPayload_NackRequest ?
      reinterpret_cast<rts::network::NackRequestT *>(value) : nullptr;
  }
  const rts::network::NackRequestT *AsNackRequest() const {
    return type == TcpPayload_NackRequest ?
      reinterpret_cast<const rts::network::NackRequestT *>(value) : nullptr;
  }
  rts::network::KeyframeSnapshotT *AsKeyframeSnapshot() {
    return type == TcpPayload_KeyframeSnapshot ?
      reinterpret_cast<rts::network::KeyframeSnapshotT *>(value) : nullptr;
  }
  const rts::network::KeyframeSnapshotT *AsKeyframeSnapshot() const {
    return type == TcpPayload_KeyframeSnapshot ?
      reinterpret_cast<const rts::network::KeyframeSnapshotT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyTcpPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, TcpPayload type);
template <bool B = false>
bool VerifyTcpPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) RLERun FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t owner_id_;
  uint16_t count_;

 public:
  RLERun()
      : owner_id_(0),
        count_(0) {
  }
  RLERun(uint16_t _owner_id, uint16_t _count)
      : owner_id_(::flatbuffers::EndianScalar(_owner_id)),
        count_(::flatbuffers::EndianScalar(_count)) {
  }
  uint16_t owner_id() const {
    return ::flatbuffers::EndianScalar(owner_id_);
  }
  uint16_t count() const {
    return ::flatbuffers::EndianScalar(count_);
  }
};
FLATBUFFERS_STRUCT_END(RLERun, 4);

struct AttackCmdT : public ::flatbuffers::NativeTable {
  typedef AttackCmd TableType;
  uint16_t target_player_id = 0;
  uint8_t percentage = 0;
};

struct AttackCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AttackCmdT NativeTableType;
  typedef AttackCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PLAYER_ID = 4,
    VT_PERCENTAGE = 6
  };
  uint16_t target_player_id() const {
    return GetField<uint16_t>(VT_TARGET_PLAYER_ID, 0);
  }
  uint8_t percentage() const {
    return GetField<uint8_t>(VT_PERCENTAGE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TARGET_PLAYER_ID, 2) &&
           VerifyField<uint8_t>(verifier, VT_PERCENTAGE, 1) &&
           verifier.EndTable();
  }
  AttackCmdT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AttackCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AttackCmd> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AttackCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AttackCmdBuilder {
  typedef AttackCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_player_id(uint16_t target_player_id) {
    fbb_.AddElement<uint16_t>(AttackCmd::VT_TARGET_PLAYER_ID, target_player_id, 0);
  }
  void add_percentage(uint8_t percentage) {
    fbb_.AddElement<uint8_t>(AttackCmd::VT_PERCENTAGE, percentage, 0);
  }
  explicit AttackCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AttackCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AttackCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AttackCmd> CreateAttackCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t target_player_id = 0,
    uint8_t percentage = 0) {
  AttackCmdBuilder builder_(_fbb);
  builder_.add_target_player_id(target_player_id);
  builder_.add_percentage(percentage);
  return builder_.Finish();
}

::flatbuffers::Offset<AttackCmd> CreateAttackCmd(::flatbuffers::FlatBufferBuilder &_fbb, const AttackCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RetreatCmdT : public ::flatbuffers::NativeTable {
  typedef RetreatCmd TableType;
  uint16_t target_player_id = 0;
};

struct RetreatCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RetreatCmdT NativeTableType;
  typedef RetreatCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PLAYER_ID = 4
  };
  uint16_t target_player_id() const {
    return GetField<uint16_t>(VT_TARGET_PLAYER_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TARGET_PLAYER_ID, 2) &&
           verifier.EndTable();
  }
  RetreatCmdT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RetreatCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RetreatCmd> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RetreatCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RetreatCmdBuilder {
  typedef RetreatCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_player_id(uint16_t target_player_id) {
    fbb_.AddElement<uint16_t>(RetreatCmd::VT_TARGET_PLAYER_ID, target_player_id, 0);
  }
  explicit RetreatCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RetreatCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RetreatCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RetreatCmd> CreateRetreatCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t target_player_id = 0) {
  RetreatCmdBuilder builder_(_fbb);
  builder_.add_target_player_id(target_player_id);
  return builder_.Finish();
}

::flatbuffers::Offset<RetreatCmd> CreateRetreatCmd(::flatbuffers::FlatBufferBuilder &_fbb, const RetreatCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CounterAttackCmdT : public ::flatbuffers::NativeTable {
  typedef CounterAttackCmd TableType;
  uint16_t target_player_id = 0;
};

struct CounterAttackCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CounterAttackCmdT NativeTableType;
  typedef CounterAttackCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PLAYER_ID = 4
  };
  uint16_t target_player_id() const {
    return GetField<uint16_t>(VT_TARGET_PLAYER_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TARGET_PLAYER_ID, 2) &&
           verifier.EndTable();
  }
  CounterAttackCmdT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CounterAttackCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CounterAttackCmd> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CounterAttackCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CounterAttackCmdBuilder {
  typedef CounterAttackCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_player_id(uint16_t target_player_id) {
    fbb_.AddElement<uint16_t>(CounterAttackCmd::VT_TARGET_PLAYER_ID, target_player_id, 0);
  }
  explicit CounterAttackCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CounterAttackCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CounterAttackCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CounterAttackCmd> CreateCounterAttackCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t target_player_id = 0) {
  CounterAttackCmdBuilder builder_(_fbb);
  builder_.add_target_player_id(target_player_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CounterAttackCmd> CreateCounterAttackCmd(::flatbuffers::FlatBufferBuilder &_fbb, const CounterAttackCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetRatioCmdT : public ::flatbuffers::NativeTable {
  typedef SetRatioCmd TableType;
  uint8_t ratio = 0;
};

struct SetRatioCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetRatioCmdT NativeTableType;
  typedef SetRatioCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RATIO = 4
  };
  uint8_t ratio() const {
    return GetField<uint8_t>(VT_RATIO, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_RATIO, 1) &&
           verifier.EndTable();
  }
  SetRatioCmdT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetRatioCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetRatioCmd> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetRatioCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetRatioCmdBuilder {
  typedef SetRatioCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ratio(uint8_t ratio) {
    fbb_.AddElement<uint8_t>(SetRatioCmd::VT_RATIO, ratio, 0);
  }
  explicit SetRatioCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetRatioCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetRatioCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetRatioCmd> CreateSetRatioCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t ratio = 0) {
  SetRatioCmdBuilder builder_(_fbb);
  builder_.add_ratio(ratio);
  return builder_.Finish();
}

::flatbuffers::Offset<SetRatioCmd> CreateSetRatioCmd(::flatbuffers::FlatBufferBuilder &_fbb, const SetRatioCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BuyUrbanizationCmdT : public ::flatbuffers::NativeTable {
  typedef BuyUrbanizationCmd TableType;
  uint8_t amount = 0;
};

struct BuyUrbanizationCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BuyUrbanizationCmdT NativeTableType;
  typedef BuyUrbanizationCmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AMOUNT = 4
  };
  uint8_t amount() const {
    return GetField<uint8_t>(VT_AMOUNT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_AMOUNT, 1) &&
           verifier.EndTable();
  }
  BuyUrbanizationCmdT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BuyUrbanizationCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BuyUrbanizationCmd> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BuyUrbanizationCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BuyUrbanizationCmdBuilder {
  typedef BuyUrbanizationCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_amount(uint8_t amount) {
    fbb_.AddElement<uint8_t>(BuyUrbanizationCmd::VT_AMOUNT, amount, 0);
  }
  explicit BuyUrbanizationCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BuyUrbanizationCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BuyUrbanizationCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BuyUrbanizationCmd> CreateBuyUrbanizationCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t amount = 0) {
  BuyUrbanizationCmdBuilder builder_(_fbb);
  builder_.add_amount(amount);
  return builder_.Finish();
}

::flatbuffers::Offset<BuyUrbanizationCmd> CreateBuyUrbanizationCmd(::flatbuffers::FlatBufferBuilder &_fbb, const BuyUrbanizationCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PlayerCommandT : public ::flatbuffers::NativeTable {
  typedef PlayerCommand TableType;
  uint16_t player_id = 0;
  rts::network::CommandPayloadUnion payload{};
};

struct PlayerCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerCommandT NativeTableType;
  typedef PlayerCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  uint16_t player_id() const {
    return GetField<uint16_t>(VT_PLAYER_ID, 0);
  }
  rts::network::CommandPayload payload_type() const {
    return static_cast<rts::network::CommandPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const rts::network::AttackCmd *payload_as_AttackCmd() const {
    return payload_type() == rts::network::CommandPayload_AttackCmd ? static_cast<const rts::network::AttackCmd *>(payload()) : nullptr;
  }
  const rts::network::RetreatCmd *payload_as_RetreatCmd() const {
    return payload_type() == rts::network::CommandPayload_RetreatCmd ? static_cast<const rts::network::RetreatCmd *>(payload()) : nullptr;
  }
  const rts::network::CounterAttackCmd *payload_as_CounterAttackCmd() const {
    return payload_type() == rts::network::CommandPayload_CounterAttackCmd ? static_cast<const rts::network::CounterAttackCmd *>(payload()) : nullptr;
  }
  const rts::network::SetRatioCmd *payload_as_SetRatioCmd() const {
    return payload_type() == rts::network::CommandPayload_SetRatioCmd ? static_cast<const rts::network::SetRatioCmd *>(payload()) : nullptr;
  }
  const rts::network::BuyUrbanizationCmd *payload_as_BuyUrbanizationCmd() const {
    return payload_type() == rts::network::CommandPayload_BuyUrbanizationCmd ? static_cast<const rts::network::BuyUrbanizationCmd *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PLAYER_ID, 2) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyCommandPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  PlayerCommandT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlayerCommandT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PlayerCommand> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerCommandT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const rts::network::AttackCmd *PlayerCommand::payload_as<rts::network::AttackCmd>() const {
  return payload_as_AttackCmd();
}

template<> inline const rts::network::RetreatCmd *PlayerCommand::payload_as<rts::network::RetreatCmd>() const {
  return payload_as_RetreatCmd();
}

template<> inline const rts::network::CounterAttackCmd *PlayerCommand::payload_as<rts::network::CounterAttackCmd>() const {
  return payload_as_CounterAttackCmd();
}

template<> inline const rts::network::SetRatioCmd *PlayerCommand::payload_as<rts::network::SetRatioCmd>() const {
  return payload_as_SetRatioCmd();
}

template<> inline const rts::network::BuyUrbanizationCmd *PlayerCommand::payload_as<rts::network::BuyUrbanizationCmd>() const {
  return payload_as_BuyUrbanizationCmd();
}

struct PlayerCommandBuilder {
  typedef PlayerCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint16_t player_id) {
    fbb_.AddElement<uint16_t>(PlayerCommand::VT_PLAYER_ID, player_id, 0);
  }
  void add_payload_type(rts::network::CommandPayload payload_type) {
    fbb_.AddElement<uint8_t>(PlayerCommand::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(PlayerCommand::VT_PAYLOAD, payload);
  }
  explicit PlayerCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerCommand> CreatePlayerCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t player_id = 0,
    rts::network::CommandPayload payload_type = rts::network::CommandPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  PlayerCommandBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_player_id(player_id);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<PlayerCommand> CreatePlayerCommand(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerCommandT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ChunkDeltaT : public ::flatbuffers::NativeTable {
  typedef ChunkDelta TableType;
  uint16_t chunk_id = 0;
  std::vector<rts::network::RLERun> runs{};
};

struct ChunkDelta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChunkDeltaT NativeTableType;
  typedef ChunkDeltaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHUNK_ID = 4,
    VT_RUNS = 6
  };
  uint16_t chunk_id() const {
    return GetField<uint16_t>(VT_CHUNK_ID, 0);
  }
  const ::flatbuffers::Vector<const rts::network::RLERun *> *runs() const {
    return GetPointer<const ::flatbuffers::Vector<const rts::network::RLERun *> *>(VT_RUNS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_CHUNK_ID, 2) &&
           VerifyOffset(verifier, VT_RUNS) &&
           verifier.VerifyVector(runs()) &&
           verifier.EndTable();
  }
  ChunkDeltaT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ChunkDeltaT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ChunkDelta> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ChunkDeltaT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ChunkDeltaBuilder {
  typedef ChunkDelta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_chunk_id(uint16_t chunk_id) {
    fbb_.AddElement<uint16_t>(ChunkDelta::VT_CHUNK_ID, chunk_id, 0);
  }
  void add_runs(::flatbuffers::Offset<::flatbuffers::Vector<const rts::network::RLERun *>> runs) {
    fbb_.AddOffset(ChunkDelta::VT_RUNS, runs);
  }
  explicit ChunkDeltaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChunkDelta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChunkDelta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChunkDelta> CreateChunkDelta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t chunk_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const rts::network::RLERun *>> runs = 0) {
  ChunkDeltaBuilder builder_(_fbb);
  builder_.add_runs(runs);
  builder_.add_chunk_id(chunk_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ChunkDelta> CreateChunkDeltaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t chunk_id = 0,
    const std::vector<rts::network::RLERun> *runs = nullptr) {
  auto runs__ = runs ? _fbb.CreateVectorOfStructs<rts::network::RLERun>(*runs) : 0;
  return rts::network::CreateChunkDelta(
      _fbb,
      chunk_id,
      runs__);
}

::flatbuffers::Offset<ChunkDelta> CreateChunkDelta(::flatbuffers::FlatBufferBuilder &_fbb, const ChunkDeltaT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TickDeltaT : public ::flatbuffers::NativeTable {
  typedef TickDelta TableType;
  uint32_t tick_number = 0;
  std::vector<std::unique_ptr<rts::network::ChunkDeltaT>> chunks{};
  TickDeltaT() = default;
  TickDeltaT(const TickDeltaT &o);
  TickDeltaT(TickDeltaT&&) FLATBUFFERS_NOEXCEPT = default;
  TickDeltaT &operator=(TickDeltaT o) FLATBUFFERS_NOEXCEPT;
};

struct TickDelta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TickDeltaT NativeTableType;
  typedef TickDeltaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK_NUMBER = 4,
    VT_CHUNKS = 6
  };
  uint32_t tick_number() const {
    return GetField<uint32_t>(VT_TICK_NUMBER, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>> *chunks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>> *>(VT_CHUNKS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TICK_NUMBER, 4) &&
           VerifyOffset(verifier, VT_CHUNKS) &&
           verifier.VerifyVector(chunks()) &&
           verifier.VerifyVectorOfTables(chunks()) &&
           verifier.EndTable();
  }
  TickDeltaT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TickDeltaT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TickDelta> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TickDeltaT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TickDeltaBuilder {
  typedef TickDelta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tick_number(uint32_t tick_number) {
    fbb_.AddElement<uint32_t>(TickDelta::VT_TICK_NUMBER, tick_number, 0);
  }
  void add_chunks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>>> chunks) {
    fbb_.AddOffset(TickDelta::VT_CHUNKS, chunks);
  }
  explicit TickDeltaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TickDelta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TickDelta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TickDelta> CreateTickDelta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick_number = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>>> chunks = 0) {
  TickDeltaBuilder builder_(_fbb);
  builder_.add_chunks(chunks);
  builder_.add_tick_number(tick_number);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TickDelta> CreateTickDeltaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick_number = 0,
    const std::vector<::flatbuffers::Offset<rts::network::ChunkDelta>> *chunks = nullptr) {
  auto chunks__ = chunks ? _fbb.CreateVector<::flatbuffers::Offset<rts::network::ChunkDelta>>(*chunks) : 0;
  return rts::network::CreateTickDelta(
      _fbb,
      tick_number,
      chunks__);
}

::flatbuffers::Offset<TickDelta> CreateTickDelta(::flatbuffers::FlatBufferBuilder &_fbb, const TickDeltaT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct UdpStatePacketT : public ::flatbuffers::NativeTable {
  typedef UdpStatePacket TableType;
  uint32_t current_tick = 0;
  uint8_t history_depth = 0;
  std::vector<std::unique_ptr<rts::network::TickDeltaT>> deltas{};
  UdpStatePacketT() = default;
  UdpStatePacketT(const UdpStatePacketT &o);
  UdpStatePacketT(UdpStatePacketT&&) FLATBUFFERS_NOEXCEPT = default;
  UdpStatePacketT &operator=(UdpStatePacketT o) FLATBUFFERS_NOEXCEPT;
};

struct UdpStatePacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UdpStatePacketT NativeTableType;
  typedef UdpStatePacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CURRENT_TICK = 4,
    VT_HISTORY_DEPTH = 6,
    VT_DELTAS = 8
  };
  uint32_t current_tick() const {
    return GetField<uint32_t>(VT_CURRENT_TICK, 0);
  }
  uint8_t history_depth() const {
    return GetField<uint8_t>(VT_HISTORY_DEPTH, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<rts::network::TickDelta>> *deltas() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<rts::network::TickDelta>> *>(VT_DELTAS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CURRENT_TICK, 4) &&
           VerifyField<uint8_t>(verifier, VT_HISTORY_DEPTH, 1) &&
           VerifyOffset(verifier, VT_DELTAS) &&
           verifier.VerifyVector(deltas()) &&
           verifier.VerifyVectorOfTables(deltas()) &&
           verifier.EndTable();
  }
  UdpStatePacketT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UdpStatePacketT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<UdpStatePacket> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UdpStatePacketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UdpStatePacketBuilder {
  typedef UdpStatePacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_current_tick(uint32_t current_tick) {
    fbb_.AddElement<uint32_t>(UdpStatePacket::VT_CURRENT_TICK, current_tick, 0);
  }
  void add_history_depth(uint8_t history_depth) {
    fbb_.AddElement<uint8_t>(UdpStatePacket::VT_HISTORY_DEPTH, history_depth, 0);
  }
  void add_deltas(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<rts::network::TickDelta>>> deltas) {
    fbb_.AddOffset(UdpStatePacket::VT_DELTAS, deltas);
  }
  explicit UdpStatePacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UdpStatePacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UdpStatePacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UdpStatePacket> CreateUdpStatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t current_tick = 0,
    uint8_t history_depth = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<rts::network::TickDelta>>> deltas = 0) {
  UdpStatePacketBuilder builder_(_fbb);
  builder_.add_deltas(deltas);
  builder_.add_current_tick(current_tick);
  builder_.add_history_depth(history_depth);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UdpStatePacket> CreateUdpStatePacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t current_tick = 0,
    uint8_t history_depth = 0,
    const std::vector<::flatbuffers::Offset<rts::network::TickDelta>> *deltas = nullptr) {
  auto deltas__ = deltas ? _fbb.CreateVector<::flatbuffers::Offset<rts::network::TickDelta>>(*deltas) : 0;
  return rts::network::CreateUdpStatePacket(
      _fbb,
      current_tick,
      history_depth,
      deltas__);
}

::flatbuffers::Offset<UdpStatePacket> CreateUdpStatePacket(::flatbuffers::FlatBufferBuilder &_fbb, const UdpStatePacketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct HandshakeRequestT : public ::flatbuffers::NativeTable {
  typedef HandshakeRequest TableType;
  uint32_t protocol_version = 0;
  std::string auth_token{};
};

struct HandshakeRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HandshakeRequestT NativeTableType;
  typedef HandshakeRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROTOCOL_VERSION = 4,
    VT_AUTH_TOKEN = 6
  };
  uint32_t protocol_version() const {
    return GetField<uint32_t>(VT_PROTOCOL_VERSION, 0);
  }
  const ::flatbuffers::String *auth_token() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AUTH_TOKEN);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PROTOCOL_VERSION, 4) &&
           VerifyOffset(verifier, VT_AUTH_TOKEN) &&
           verifier.VerifyString(auth_token()) &&
           verifier.EndTable();
  }
  HandshakeRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(HandshakeRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<HandshakeRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct HandshakeRequestBuilder {
  typedef HandshakeRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_protocol_version(uint32_t protocol_version) {
    fbb_.AddElement<uint32_t>(HandshakeRequest::VT_PROTOCOL_VERSION, protocol_version, 0);
  }
  void add_auth_token(::flatbuffers::Offset<::flatbuffers::String> auth_token) {
    fbb_.AddOffset(HandshakeRequest::VT_AUTH_TOKEN, auth_token);
  }
  explicit HandshakeRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HandshakeRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HandshakeRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HandshakeRequest> CreateHandshakeRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t protocol_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> auth_token = 0) {
  HandshakeRequestBuilder builder_(_fbb);
  builder_.add_auth_token(auth_token);
  builder_.add_protocol_version(protocol_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HandshakeRequest> CreateHandshakeRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t protocol_version = 0,
    const char *auth_token = nullptr) {
  auto auth_token__ = auth_token ? _fbb.CreateString(auth_token) : 0;
  return rts::network::CreateHandshakeRequest(
      _fbb,
      protocol_version,
      auth_token__);
}

::flatbuffers::Offset<HandshakeRequest> CreateHandshakeRequest(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct HandshakeResponseT : public ::flatbuffers::NativeTable {
  typedef HandshakeResponse TableType;
  bool accepted = false;
  uint16_t assigned_player_id = 0;
  std::string session_uuid{};
};

struct HandshakeResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HandshakeResponseT NativeTableType;
  typedef HandshakeResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCEPTED = 4,
    VT_ASSIGNED_PLAYER_ID = 6,
    VT_SESSION_UUID = 8
  };
  bool accepted() const {
    return GetField<uint8_t>(VT_ACCEPTED, 0) != 0;
  }
  uint16_t assigned_player_id() const {
    return GetField<uint16_t>(VT_ASSIGNED_PLAYER_ID, 0);
  }
  const ::flatbuffers::String *session_uuid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SESSION_UUID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ACCEPTED, 1) &&
           VerifyField<uint16_t>(verifier, VT_ASSIGNED_PLAYER_ID, 2) &&
           VerifyOffset(verifier, VT_SESSION_UUID) &&
           verifier.VerifyString(session_uuid()) &&
           verifier.EndTable();
  }
  HandshakeResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(HandshakeResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<HandshakeResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct HandshakeResponseBuilder {
  typedef HandshakeResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_accepted(bool accepted) {
    fbb_.AddElement<uint8_t>(HandshakeResponse::VT_ACCEPTED, static_cast<uint8_t>(accepted), 0);
  }
  void add_assigned_player_id(uint16_t assigned_player_id) {
    fbb_.AddElement<uint16_t>(HandshakeResponse::VT_ASSIGNED_PLAYER_ID, assigned_player_id, 0);
  }
  void add_session_uuid(::flatbuffers::Offset<::flatbuffers::String> session_uuid) {
    fbb_.AddOffset(HandshakeResponse::VT_SESSION_UUID, session_uuid);
  }
  explicit HandshakeResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HandshakeResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HandshakeResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HandshakeResponse> CreateHandshakeResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool accepted = false,
    uint16_t assigned_player_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> session_uuid = 0) {
  HandshakeResponseBuilder builder_(_fbb);
  builder_.add_session_uuid(session_uuid);
  builder_.add_assigned_player_id(assigned_player_id);
  builder_.add_accepted(accepted);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HandshakeResponse> CreateHandshakeResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool accepted = false,
    uint16_t assigned_player_id = 0,
    const char *session_uuid = nullptr) {
  auto session_uuid__ = session_uuid ? _fbb.CreateString(session_uuid) : 0;
  return rts::network::CreateHandshakeResponse(
      _fbb,
      accepted,
      assigned_player_id,
      session_uuid__);
}

::flatbuffers::Offset<HandshakeResponse> CreateHandshakeResponse(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct NackRequestT : public ::flatbuffers::NativeTable {
  typedef NackRequest TableType;
  uint32_t last_known_tick = 0;
};

struct NackRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NackRequestT NativeTableType;
  typedef NackRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LAST_KNOWN_TICK = 4
  };
  uint32_t last_known_tick() const {
    return GetField<uint32_t>(VT_LAST_KNOWN_TICK, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_LAST_KNOWN_TICK, 4) &&
           verifier.EndTable();
  }
  NackRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NackRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<NackRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NackRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NackRequestBuilder {
  typedef NackRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_last_known_tick(uint32_t last_known_tick) {
    fbb_.AddElement<uint32_t>(NackRequest::VT_LAST_KNOWN_TICK, last_known_tick, 0);
  }
  explicit NackRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NackRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NackRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NackRequest> CreateNackRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t last_known_tick = 0) {
  NackRequestBuilder builder_(_fbb);
  builder_.add_last_known_tick(last_known_tick);
  return builder_.Finish();
}

::flatbuffers::Offset<NackRequest> CreateNackRequest(::flatbuffers::FlatBufferBuilder &_fbb, const NackRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct KeyframeSnapshotT : public ::flatbuffers::NativeTable {
  typedef KeyframeSnapshot TableType;
  uint32_t tick_number = 0;
  std::vector<std::unique_ptr<rts::network::ChunkDeltaT>> all_chunks{};
  KeyframeSnapshotT() = default;
  KeyframeSnapshotT(const KeyframeSnapshotT &o);
  KeyframeSnapshotT(KeyframeSnapshotT&&) FLATBUFFERS_NOEXCEPT = default;
  KeyframeSnapshotT &operator=(KeyframeSnapshotT o) FLATBUFFERS_NOEXCEPT;
};

struct KeyframeSnapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyframeSnapshotT NativeTableType;
  typedef KeyframeSnapshotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK_NUMBER = 4,
    VT_ALL_CHUNKS = 6
  };
  uint32_t tick_number() const {
    return GetField<uint32_t>(VT_TICK_NUMBER, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>> *all_chunks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>> *>(VT_ALL_CHUNKS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TICK_NUMBER, 4) &&
           VerifyOffset(verifier, VT_ALL_CHUNKS) &&
           verifier.VerifyVector(all_chunks()) &&
           verifier.VerifyVectorOfTables(all_chunks()) &&
           verifier.EndTable();
  }
  KeyframeSnapshotT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(KeyframeSnapshotT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<KeyframeSnapshot> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const KeyframeSnapshotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct KeyframeSnapshotBuilder {
  typedef KeyframeSnapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tick_number(uint32_t tick_number) {
    fbb_.AddElement<uint32_t>(KeyframeSnapshot::VT_TICK_NUMBER, tick_number, 0);
  }
  void add_all_chunks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>>> all_chunks) {
    fbb_.AddOffset(KeyframeSnapshot::VT_ALL_CHUNKS, all_chunks);
  }
  explicit KeyframeSnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyframeSnapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyframeSnapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyframeSnapshot> CreateKeyframeSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick_number = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<rts::network::ChunkDelta>>> all_chunks = 0) {
  KeyframeSnapshotBuilder builder_(_fbb);
  builder_.add_all_chunks(all_chunks);
  builder_.add_tick_number(tick_number);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KeyframeSnapshot> CreateKeyframeSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick_number = 0,
    const std::vector<::flatbuffers::Offset<rts::network::ChunkDelta>> *all_chunks = nullptr) {
  auto all_chunks__ = all_chunks ? _fbb.CreateVector<::flatbuffers::Offset<rts::network::ChunkDelta>>(*all_chunks) : 0;
  return rts::network::CreateKeyframeSnapshot(
      _fbb,
      tick_number,
      all_chunks__);
}

::flatbuffers::Offset<KeyframeSnapshot> CreateKeyframeSnapshot(::flatbuffers::FlatBufferBuilder &_fbb, const KeyframeSnapshotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TcpMessageT : public ::flatbuffers::NativeTable {
  typedef TcpMessage TableType;
  rts::network::TcpPayloadUnion payload{};
};

struct TcpMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TcpMessageT NativeTableType;
  typedef TcpMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  rts::network::TcpPayload payload_type() const {
    return static_cast<rts::network::TcpPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const rts::network::PlayerCommand *payload_as_PlayerCommand() const {
    return payload_type() == rts::network::TcpPayload_PlayerCommand ? static_cast<const rts::network::PlayerCommand *>(payload()) : nullptr;
  }
  const rts::network::HandshakeRequest *payload_as_HandshakeRequest() const {
    return payload_type() == rts::network::TcpPayload_HandshakeRequest ? static_cast<const rts::network::HandshakeRequest *>(payload()) : nullptr;
  }
  const rts::network::HandshakeResponse *payload_as_HandshakeResponse() const {
    return payload_type() == rts::network::TcpPayload_HandshakeResponse ? static_cast<const rts::network::HandshakeResponse *>(payload()) : nullptr;
  }
  const rts::network::NackRequest *payload_as_NackRequest() const {
    return payload_type() == rts::network::TcpPayload_NackRequest ? static_cast<const rts::network::NackRequest *>(payload()) : nullptr;
  }
  const rts::network::KeyframeSnapshot *payload_as_KeyframeSnapshot() const {
    return payload_type() == rts::network::TcpPayload_KeyframeSnapshot ? static_cast<const rts::network::KeyframeSnapshot *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyTcpPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  TcpMessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TcpMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TcpMessage> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TcpMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const rts::network::PlayerCommand *TcpMessage::payload_as<rts::network::PlayerCommand>() const {
  return payload_as_PlayerCommand();
}

template<> inline const rts::network::HandshakeRequest *TcpMessage::payload_as<rts::network::HandshakeRequest>() const {
  return payload_as_HandshakeRequest();
}

template<> inline const rts::network::HandshakeResponse *TcpMessage::payload_as<rts::network::HandshakeResponse>() const {
  return payload_as_HandshakeResponse();
}

template<> inline const rts::network::NackRequest *TcpMessage::payload_as<rts::network::NackRequest>() const {
  return payload_as_NackRequest();
}

template<> inline const rts::network::KeyframeSnapshot *TcpMessage::payload_as<rts::network::KeyframeSnapshot>() const {
  return payload_as_KeyframeSnapshot();
}

struct TcpMessageBuilder {
  typedef TcpMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(rts::network::TcpPayload payload_type) {
    fbb_.AddElement<uint8_t>(TcpMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(TcpMessage::VT_PAYLOAD, payload);
  }
  explicit TcpMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TcpMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TcpMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TcpMessage> CreateTcpMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    rts::network::TcpPayload payload_type = rts::network::TcpPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  TcpMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<TcpMessage> CreateTcpMessage(::flatbuffers::FlatBufferBuilder &_fbb, const TcpMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline AttackCmdT *AttackCmd::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AttackCmdT>(new AttackCmdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AttackCmd::UnPackTo(AttackCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = target_player_id(); _o->target_player_id = _e; }
  { auto _e = percentage(); _o->percentage = _e; }
}

inline ::flatbuffers::Offset<AttackCmd> CreateAttackCmd(::flatbuffers::FlatBufferBuilder &_fbb, const AttackCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return AttackCmd::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AttackCmd> AttackCmd::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AttackCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AttackCmdT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _target_player_id = _o->target_player_id;
  auto _percentage = _o->percentage;
  return rts::network::CreateAttackCmd(
      _fbb,
      _target_player_id,
      _percentage);
}

inline RetreatCmdT *RetreatCmd::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RetreatCmdT>(new RetreatCmdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RetreatCmd::UnPackTo(RetreatCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = target_player_id(); _o->target_player_id = _e; }
}

inline ::flatbuffers::Offset<RetreatCmd> CreateRetreatCmd(::flatbuffers::FlatBufferBuilder &_fbb, const RetreatCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return RetreatCmd::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RetreatCmd> RetreatCmd::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RetreatCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RetreatCmdT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _target_player_id = _o->target_player_id;
  return rts::network::CreateRetreatCmd(
      _fbb,
      _target_player_id);
}

inline CounterAttackCmdT *CounterAttackCmd::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CounterAttackCmdT>(new CounterAttackCmdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CounterAttackCmd::UnPackTo(CounterAttackCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = target_player_id(); _o->target_player_id = _e; }
}

inline ::flatbuffers::Offset<CounterAttackCmd> CreateCounterAttackCmd(::flatbuffers::FlatBufferBuilder &_fbb, const CounterAttackCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CounterAttackCmd::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CounterAttackCmd> CounterAttackCmd::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CounterAttackCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CounterAttackCmdT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _target_player_id = _o->target_player_id;
  return rts::network::CreateCounterAttackCmd(
      _fbb,
      _target_player_id);
}

inline SetRatioCmdT *SetRatioCmd::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetRatioCmdT>(new SetRatioCmdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetRatioCmd::UnPackTo(SetRatioCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ratio(); _o->ratio = _e; }
}

inline ::flatbuffers::Offset<SetRatioCmd> CreateSetRatioCmd(::flatbuffers::FlatBufferBuilder &_fbb, const SetRatioCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SetRatioCmd::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetRatioCmd> SetRatioCmd::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetRatioCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetRatioCmdT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ratio = _o->ratio;
  return rts::network::CreateSetRatioCmd(
      _fbb,
      _ratio);
}

inline BuyUrbanizationCmdT *BuyUrbanizationCmd::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BuyUrbanizationCmdT>(new BuyUrbanizationCmdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BuyUrbanizationCmd::UnPackTo(BuyUrbanizationCmdT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = amount(); _o->amount = _e; }
}

inline ::flatbuffers::Offset<BuyUrbanizationCmd> CreateBuyUrbanizationCmd(::flatbuffers::FlatBufferBuilder &_fbb, const BuyUrbanizationCmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return BuyUrbanizationCmd::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BuyUrbanizationCmd> BuyUrbanizationCmd::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BuyUrbanizationCmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BuyUrbanizationCmdT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _amount = _o->amount;
  return rts::network::CreateBuyUrbanizationCmd(
      _fbb,
      _amount);
}

inline PlayerCommandT *PlayerCommand::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PlayerCommandT>(new PlayerCommandT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PlayerCommand::UnPackTo(PlayerCommandT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player_id(); _o->player_id = _e; }
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = rts::network::CommandPayloadUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<PlayerCommand> CreatePlayerCommand(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerCommandT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return PlayerCommand::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PlayerCommand> PlayerCommand::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerCommandT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PlayerCommandT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player_id = _o->player_id;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return rts::network::CreatePlayerCommand(
      _fbb,
      _player_id,
      _payload_type,
      _payload);
}

inline ChunkDeltaT *ChunkDelta::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ChunkDeltaT>(new ChunkDeltaT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ChunkDelta::UnPackTo(ChunkDeltaT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = chunk_id(); _o->chunk_id = _e; }
  { auto _e = runs(); if (_e) { _o->runs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->runs[_i] = *_e->Get(_i); } } else { _o->runs.resize(0); } }
}

inline ::flatbuffers::Offset<ChunkDelta> CreateChunkDelta(::flatbuffers::FlatBufferBuilder &_fbb, const ChunkDeltaT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ChunkDelta::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ChunkDelta> ChunkDelta::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ChunkDeltaT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ChunkDeltaT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _chunk_id = _o->chunk_id;
  auto _runs = _o->runs.size() ? _fbb.CreateVectorOfStructs(_o->runs) : 0;
  return rts::network::CreateChunkDelta(
      _fbb,
      _chunk_id,
      _runs);
}

inline TickDeltaT::TickDeltaT(const TickDeltaT &o)
      : tick_number(o.tick_number) {
  chunks.reserve(o.chunks.size());
  for (const auto &chunks_ : o.chunks) { chunks.emplace_back((chunks_) ? new rts::network::ChunkDeltaT(*chunks_) : nullptr); }
}

inline TickDeltaT &TickDeltaT::operator=(TickDeltaT o) FLATBUFFERS_NOEXCEPT {
  std::swap(tick_number, o.tick_number);
  std::swap(chunks, o.chunks);
  return *this;
}

inline TickDeltaT *TickDelta::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TickDeltaT>(new TickDeltaT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TickDelta::UnPackTo(TickDeltaT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = tick_number(); _o->tick_number = _e; }
  { auto _e = chunks(); if (_e) { _o->chunks.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->chunks[_i]) { _e->Get(_i)->UnPackTo(_o->chunks[_i].get(), _resolver); } else { _o->chunks[_i] = std::unique_ptr<rts::network::ChunkDeltaT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->chunks.resize(0); } }
}

inline ::flatbuffers::Offset<TickDelta> CreateTickDelta(::flatbuffers::FlatBufferBuilder &_fbb, const TickDeltaT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TickDelta::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TickDelta> TickDelta::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TickDeltaT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TickDeltaT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _tick_number = _o->tick_number;
  auto _chunks = _o->chunks.size() ? _fbb.CreateVector<::flatbuffers::Offset<rts::network::ChunkDelta>> (_o->chunks.size(), [](size_t i, _VectorArgs *__va) { return CreateChunkDelta(*__va->__fbb, __va->__o->chunks[i].get(), __va->__rehasher); }, &_va ) : 0;
  return rts::network::CreateTickDelta(
      _fbb,
      _tick_number,
      _chunks);
}

inline UdpStatePacketT::UdpStatePacketT(const UdpStatePacketT &o)
      : current_tick(o.current_tick),
        history_depth(o.history_depth) {
  deltas.reserve(o.deltas.size());
  for (const auto &deltas_ : o.deltas) { deltas.emplace_back((deltas_) ? new rts::network::TickDeltaT(*deltas_) : nullptr); }
}

inline UdpStatePacketT &UdpStatePacketT::operator=(UdpStatePacketT o) FLATBUFFERS_NOEXCEPT {
  std::swap(current_tick, o.current_tick);
  std::swap(history_depth, o.history_depth);
  std::swap(deltas, o.deltas);
  return *this;
}

inline UdpStatePacketT *UdpStatePacket::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<UdpStatePacketT>(new UdpStatePacketT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UdpStatePacket::UnPackTo(UdpStatePacketT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = current_tick(); _o->current_tick = _e; }
  { auto _e = history_depth(); _o->history_depth = _e; }
  { auto _e = deltas(); if (_e) { _o->deltas.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->deltas[_i]) { _e->Get(_i)->UnPackTo(_o->deltas[_i].get(), _resolver); } else { _o->deltas[_i] = std::unique_ptr<rts::network::TickDeltaT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->deltas.resize(0); } }
}

inline ::flatbuffers::Offset<UdpStatePacket> CreateUdpStatePacket(::flatbuffers::FlatBufferBuilder &_fbb, const UdpStatePacketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return UdpStatePacket::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<UdpStatePacket> UdpStatePacket::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UdpStatePacketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const UdpStatePacketT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _current_tick = _o->current_tick;
  auto _history_depth = _o->history_depth;
  auto _deltas = _o->deltas.size() ? _fbb.CreateVector<::flatbuffers::Offset<rts::network::TickDelta>> (_o->deltas.size(), [](size_t i, _VectorArgs *__va) { return CreateTickDelta(*__va->__fbb, __va->__o->deltas[i].get(), __va->__rehasher); }, &_va ) : 0;
  return rts::network::CreateUdpStatePacket(
      _fbb,
      _current_tick,
      _history_depth,
      _deltas);
}

inline HandshakeRequestT *HandshakeRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<HandshakeRequestT>(new HandshakeRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void HandshakeRequest::UnPackTo(HandshakeRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = protocol_version(); _o->protocol_version = _e; }
  { auto _e = auth_token(); if (_e) _o->auth_token = _e->str(); }
}

inline ::flatbuffers::Offset<HandshakeRequest> CreateHandshakeRequest(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return HandshakeRequest::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<HandshakeRequest> HandshakeRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const HandshakeRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _protocol_version = _o->protocol_version;
  auto _auth_token = _o->auth_token.empty() ? 0 : _fbb.CreateString(_o->auth_token);
  return rts::network::CreateHandshakeRequest(
      _fbb,
      _protocol_version,
      _auth_token);
}

inline HandshakeResponseT *HandshakeResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<HandshakeResponseT>(new HandshakeResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void HandshakeResponse::UnPackTo(HandshakeResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = accepted(); _o->accepted = _e; }
  { auto _e = assigned_player_id(); _o->assigned_player_id = _e; }
  { auto _e = session_uuid(); if (_e) _o->session_uuid = _e->str(); }
}

inline ::flatbuffers::Offset<HandshakeResponse> CreateHandshakeResponse(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return HandshakeResponse::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<HandshakeResponse> HandshakeResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const HandshakeResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _accepted = _o->accepted;
  auto _assigned_player_id = _o->assigned_player_id;
  auto _session_uuid = _o->session_uuid.empty() ? 0 : _fbb.CreateString(_o->session_uuid);
  return rts::network::CreateHandshakeResponse(
      _fbb,
      _accepted,
      _assigned_player_id,
      _session_uuid);
}

inline NackRequestT *NackRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<NackRequestT>(new NackRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void NackRequest::UnPackTo(NackRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = last_known_tick(); _o->last_known_tick = _e; }
}

inline ::flatbuffers::Offset<NackRequest> CreateNackRequest(::flatbuffers::FlatBufferBuilder &_fbb, const NackRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return NackRequest::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<NackRequest> NackRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NackRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const NackRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _last_known_tick = _o->last_known_tick;
  return rts::network::CreateNackRequest(
      _fbb,
      _last_known_tick);
}

inline KeyframeSnapshotT::KeyframeSnapshotT(const KeyframeSnapshotT &o)
      : tick_number(o.tick_number) {
  all_chunks.reserve(o.all_chunks.size());
  for (const auto &all_chunks_ : o.all_chunks) { all_chunks.emplace_back((all_chunks_) ? new rts::network::ChunkDeltaT(*all_chunks_) : nullptr); }
}

inline KeyframeSnapshotT &KeyframeSnapshotT::operator=(KeyframeSnapshotT o) FLATBUFFERS_NOEXCEPT {
  std::swap(tick_number, o.tick_number);
  std::swap(all_chunks, o.all_chunks);
  return *this;
}

inline KeyframeSnapshotT *KeyframeSnapshot::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<KeyframeSnapshotT>(new KeyframeSnapshotT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void KeyframeSnapshot::UnPackTo(KeyframeSnapshotT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = tick_number(); _o->tick_number = _e; }
  { auto _e = all_chunks(); if (_e) { _o->all_chunks.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->all_chunks[_i]) { _e->Get(_i)->UnPackTo(_o->all_chunks[_i].get(), _resolver); } else { _o->all_chunks[_i] = std::unique_ptr<rts::network::ChunkDeltaT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->all_chunks.resize(0); } }
}

inline ::flatbuffers::Offset<KeyframeSnapshot> CreateKeyframeSnapshot(::flatbuffers::FlatBufferBuilder &_fbb, const KeyframeSnapshotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return KeyframeSnapshot::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<KeyframeSnapshot> KeyframeSnapshot::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const KeyframeSnapshotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const KeyframeSnapshotT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _tick_number = _o->tick_number;
  auto _all_chunks = _o->all_chunks.size() ? _fbb.CreateVector<::flatbuffers::Offset<rts::network::ChunkDelta>> (_o->all_chunks.size(), [](size_t i, _VectorArgs *__va) { return CreateChunkDelta(*__va->__fbb, __va->__o->all_chunks[i].get(), __va->__rehasher); }, &_va ) : 0;
  return rts::network::CreateKeyframeSnapshot(
      _fbb,
      _tick_number,
      _all_chunks);
}

inline TcpMessageT *TcpMessage::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TcpMessageT>(new TcpMessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TcpMessage::UnPackTo(TcpMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = rts::network::TcpPayloadUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<TcpMessage> CreateTcpMessage(::flatbuffers::FlatBufferBuilder &_fbb, const TcpMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TcpMessage::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TcpMessage> TcpMessage::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TcpMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TcpMessageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return rts::network::CreateTcpMessage(
      _fbb,
      _payload_type,
      _payload);
}

template <bool B>
inline bool VerifyCommandPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CommandPayload type) {
  switch (type) {
    case CommandPayload_NONE: {
      return true;
    }
    case CommandPayload_AttackCmd: {
      auto ptr = reinterpret_cast<const rts::network::AttackCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CommandPayload_RetreatCmd: {
      auto ptr = reinterpret_cast<const rts::network::RetreatCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CommandPayload_CounterAttackCmd: {
      auto ptr = reinterpret_cast<const rts::network::CounterAttackCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CommandPayload_SetRatioCmd: {
      auto ptr = reinterpret_cast<const rts::network::SetRatioCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CommandPayload_BuyUrbanizationCmd: {
      auto ptr = reinterpret_cast<const rts::network::BuyUrbanizationCmd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyCommandPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCommandPayload(
        verifier,  values->Get(i), types->GetEnum<CommandPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline void *CommandPayloadUnion::UnPack(const void *obj, CommandPayload type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case CommandPayload_AttackCmd: {
      auto ptr = reinterpret_cast<const rts::network::AttackCmd *>(obj);
      return ptr->UnPack(resolver);
    }
    case CommandPayload_RetreatCmd: {
      auto ptr = reinterpret_cast<const rts::network::RetreatCmd *>(obj);
      return ptr->UnPack(resolver);
    }
    case CommandPayload_CounterAttackCmd: {
      auto ptr = reinterpret_cast<const rts::network::CounterAttackCmd *>(obj);
      return ptr->UnPack(resolver);
    }
    case CommandPayload_SetRatioCmd: {
      auto ptr = reinterpret_cast<const rts::network::SetRatioCmd *>(obj);
      return ptr->UnPack(resolver);
    }
    case CommandPayload_BuyUrbanizationCmd: {
      auto ptr = reinterpret_cast<const rts::network::BuyUrbanizationCmd *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> CommandPayloadUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case CommandPayload_AttackCmd: {
      auto ptr = reinterpret_cast<const rts::network::AttackCmdT *>(value);
      return CreateAttackCmd(_fbb, ptr, _rehasher).Union();
    }
    case CommandPayload_RetreatCmd: {
      auto ptr = reinterpret_cast<const rts::network::RetreatCmdT *>(value);
      return CreateRetreatCmd(_fbb, ptr, _rehasher).Union();
    }
    case CommandPayload_CounterAttackCmd: {
      auto ptr = reinterpret_cast<const rts::network::CounterAttackCmdT *>(value);
      return CreateCounterAttackCmd(_fbb, ptr, _rehasher).Union();
    }
    case CommandPayload_SetRatioCmd: {
      auto ptr = reinterpret_cast<const rts::network::SetRatioCmdT *>(value);
      return CreateSetRatioCmd(_fbb, ptr, _rehasher).Union();
    }
    case CommandPayload_BuyUrbanizationCmd: {
      auto ptr = reinterpret_cast<const rts::network::BuyUrbanizationCmdT *>(value);
      return CreateBuyUrbanizationCmd(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline CommandPayloadUnion::CommandPayloadUnion(const CommandPayloadUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case CommandPayload_AttackCmd: {
      value = new rts::network::AttackCmdT(*reinterpret_cast<rts::network::AttackCmdT *>(u.value));
      break;
    }
    case CommandPayload_RetreatCmd: {
      value = new rts::network::RetreatCmdT(*reinterpret_cast<rts::network::RetreatCmdT *>(u.value));
      break;
    }
    case CommandPayload_CounterAttackCmd: {
      value = new rts::network::CounterAttackCmdT(*reinterpret_cast<rts::network::CounterAttackCmdT *>(u.value));
      break;
    }
    case CommandPayload_SetRatioCmd: {
      value = new rts::network::SetRatioCmdT(*reinterpret_cast<rts::network::SetRatioCmdT *>(u.value));
      break;
    }
    case CommandPayload_BuyUrbanizationCmd: {
      value = new rts::network::BuyUrbanizationCmdT(*reinterpret_cast<rts::network::BuyUrbanizationCmdT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void CommandPayloadUnion::Reset() {
  switch (type) {
    case CommandPayload_AttackCmd: {
      auto ptr = reinterpret_cast<rts::network::AttackCmdT *>(value);
      delete ptr;
      break;
    }
    case CommandPayload_RetreatCmd: {
      auto ptr = reinterpret_cast<rts::network::RetreatCmdT *>(value);
      delete ptr;
      break;
    }
    case CommandPayload_CounterAttackCmd: {
      auto ptr = reinterpret_cast<rts::network::CounterAttackCmdT *>(value);
      delete ptr;
      break;
    }
    case CommandPayload_SetRatioCmd: {
      auto ptr = reinterpret_cast<rts::network::SetRatioCmdT *>(value);
      delete ptr;
      break;
    }
    case CommandPayload_BuyUrbanizationCmd: {
      auto ptr = reinterpret_cast<rts::network::BuyUrbanizationCmdT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = CommandPayload_NONE;
}

template <bool B>
inline bool VerifyTcpPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, TcpPayload type) {
  switch (type) {
    case TcpPayload_NONE: {
      return true;
    }
    case TcpPayload_PlayerCommand: {
      auto ptr = reinterpret_cast<const rts::network::PlayerCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case TcpPayload_HandshakeRequest: {
      auto ptr = reinterpret_cast<const rts::network::HandshakeRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case TcpPayload_HandshakeResponse: {
      auto ptr = reinterpret_cast<const rts::network::HandshakeResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case TcpPayload_NackRequest: {
      auto ptr = reinterpret_cast<const rts::network::NackRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case TcpPayload_KeyframeSnapshot: {
      auto ptr = reinterpret_cast<const rts::network::KeyframeSnapshot *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyTcpPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyTcpPayload(
        verifier,  values->Get(i), types->GetEnum<TcpPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline void *TcpPayloadUnion::UnPack(const void *obj, TcpPayload type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case TcpPayload_PlayerCommand: {
      auto ptr = reinterpret_cast<const rts::network::PlayerCommand *>(obj);
      return ptr->UnPack(resolver);
    }
    case TcpPayload_HandshakeRequest: {
      auto ptr = reinterpret_cast<const rts::network::HandshakeRequest *>(obj);
      return ptr->UnPack(resolver);
    }
    case TcpPayload_HandshakeResponse: {
      auto ptr = reinterpret_cast<const rts::network::HandshakeResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case TcpPayload_NackRequest: {
      auto ptr = reinterpret_cast<const rts::network::NackRequest *>(obj);
      return ptr->UnPack(resolver);
    }
    case TcpPayload_KeyframeSnapshot: {
      auto ptr = reinterpret_cast<const rts::network::KeyframeSnapshot *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> TcpPayloadUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case TcpPayload_PlayerCommand: {
      auto ptr = reinterpret_cast<const rts::network::PlayerCommandT *>(value);
      return CreatePlayerCommand(_fbb, ptr, _rehasher).Union();
    }
    case TcpPayload_HandshakeRequest: {
      auto ptr = reinterpret_cast<const rts::network::HandshakeRequestT *>(value);
      return CreateHandshakeRequest(_fbb, ptr, _rehasher).Union();
    }
    case TcpPayload_HandshakeResponse: {
      auto ptr = reinterpret_cast<const rts::network::HandshakeResponseT *>(value);
      return CreateHandshakeResponse(_fbb, ptr, _rehasher).Union();
    }
    case TcpPayload_NackRequest: {
      auto ptr = reinterpret_cast<const rts::network::NackRequestT *>(value);
      return CreateNackRequest(_fbb, ptr, _rehasher).Union();
    }
    case TcpPayload_KeyframeSnapshot: {
      auto ptr = reinterpret_cast<const rts::network::KeyframeSnapshotT *>(value);
      return CreateKeyframeSnapshot(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline TcpPayloadUnion::TcpPayloadUnion(const TcpPayloadUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case TcpPayload_PlayerCommand: {
      value = new rts::network::PlayerCommandT(*reinterpret_cast<rts::network::PlayerCommandT *>(u.value));
      break;
    }
    case TcpPayload_HandshakeRequest: {
      value = new rts::network::HandshakeRequestT(*reinterpret_cast<rts::network::HandshakeRequestT *>(u.value));
      break;
    }
    case TcpPayload_HandshakeResponse: {
      value = new rts::network::HandshakeResponseT(*reinterpret_cast<rts::network::HandshakeResponseT *>(u.value));
      break;
    }
    case TcpPayload_NackRequest: {
      value = new rts::network::NackRequestT(*reinterpret_cast<rts::network::NackRequestT *>(u.value));
      break;
    }
    case TcpPayload_KeyframeSnapshot: {
      value = new rts::network::KeyframeSnapshotT(*reinterpret_cast<rts::network::KeyframeSnapshotT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void TcpPayloadUnion::Reset() {
  switch (type) {
    case TcpPayload_PlayerCommand: {
      auto ptr = reinterpret_cast<rts::network::PlayerCommandT *>(value);
      delete ptr;
      break;
    }
    case TcpPayload_HandshakeRequest: {
      auto ptr = reinterpret_cast<rts::network::HandshakeRequestT *>(value);
      delete ptr;
      break;
    }
    case TcpPayload_HandshakeResponse: {
      auto ptr = reinterpret_cast<rts::network::HandshakeResponseT *>(value);
      delete ptr;
      break;
    }
    case TcpPayload_NackRequest: {
      auto ptr = reinterpret_cast<rts::network::NackRequestT *>(value);
      delete ptr;
      break;
    }
    case TcpPayload_KeyframeSnapshot: {
      auto ptr = reinterpret_cast<rts::network::KeyframeSnapshotT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = TcpPayload_NONE;
}

inline const rts::network::UdpStatePacket *GetUdpStatePacket(const void *buf) {
  return ::flatbuffers::GetRoot<rts::network::UdpStatePacket>(buf);
}

inline const rts::network::UdpStatePacket *GetSizePrefixedUdpStatePacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<rts::network::UdpStatePacket>(buf);
}

template <bool B = false>
inline bool VerifyUdpStatePacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<rts::network::UdpStatePacket>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedUdpStatePacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<rts::network::UdpStatePacket>(nullptr);
}

inline void FinishUdpStatePacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<rts::network::UdpStatePacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUdpStatePacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<rts::network::UdpStatePacket> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<rts::network::UdpStatePacketT> UnPackUdpStatePacket(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<rts::network::UdpStatePacketT>(GetUdpStatePacket(buf)->UnPack(res));
}

inline std::unique_ptr<rts::network::UdpStatePacketT> UnPackSizePrefixedUdpStatePacket(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<rts::network::UdpStatePacketT>(GetSizePrefixedUdpStatePacket(buf)->UnPack(res));
}

}  // namespace network
}  // namespace rts

#endif  // FLATBUFFERS_GENERATED_RTSPROTOCOL_RTS_NETWORK_H_
